### ISSUE TITLE
Inlined modules get emitted in the output

### ISSUE THREAD

**Issue by Birowsky** [numical/style-ext-html-webpack-plugin#23]
I am inlining a `splash.css` and a `splash.js` file into the `index.html` using `style-ext-html-webpack-plugin` and `script-ext-html-webpack-plugin`.

The [service worker](https://github.com/NekR/offline-plugin) goes through the assets and runs into the mentioned files trying to cache them, but fails with:

> http://localhost:8080/splash.a72065b4ca5e25fbaed5.js?__uncache=3%2F20%2F2017%2C%208%3A36%3A01%20PM Failed to load resource: the server responded with a status of 404 (Not Found)

> http://localhost:8080/splash.css?__uncache=3%2F20%2F2017%2C%208%3A36%3A01%20PM Failed to load resource: the server responded with a status of 404 (Not Found)

I'm surprised because the inlined files should be forgotten after they are inlined, no?

I wanna know how to JUST inline those files and not emit them into the output. 

This might as well just be my fault since I'm not an experienced webpacker.

**Comment by numical** [comment]
Hi, sorry for the delay in responding. I'll take a look this evening.

**Comment by Birowsky** [comment]
No problem at all. Let me know if you need any more details.

**Comment by numical** [comment]
OK - I am unfamiliar with `OfflinePlugin` but I think the general issue will be the different webpack plugins not working together happily.  
`HtmlWebpackPlugin` hooks into lifecycle events emitted by Webpack.  I imagine `OfflinePlugin` does the same.   `Style-ext...` and `Script-ext...` plugins then hook into events emitted by `HtmlWepbackPlugin`.
Whilst  `Style-ext...` and `Script-ext...`  do remove the in-lined assets from the compilation, I suspect the choreography of all these events is such that they do so after `OfflinePlugin` has recorded the assets.  
Rather than try to untangle all of this I suggest the easiest approach (certainly for me!) is for you to use [exclude asset option](https://github.com/NekR/offline-plugin/blob/master/docs/options.md#excludes-arraystring--globs_pattern) of `OfflinePlugin`. 
Does this work / is it sufficient for your needs?

**Comment by Birowsky** [comment]
Unfamiliar with OfflinePlugin?? But it's the future! xD

I used `exclude` as you said and obviously enough, it excluded the files.

So yeah.. thanx for reading the docs for me :}
