### ISSUE TITLE
I have weird critical inline style behaviour.

### ISSUE THREAD

**Issue by JustFly1984** [numical/style-ext-html-webpack-plugin#3]
I have three style tags instead of two.

1st style contains my critical css, but it has no type="text/css" attribute.

2nd style tag is empty, but it has  type="text/css" attribute. It should not be there.

3rd style tag contain all other css and it has type="text/css" attribute.

It is not critical, everything works thou.

**Comment by numical** [comment]
That's odd.
Can I see your webpack.config.js and any template you are using for your html file?
If you do not want these public, send to mike.evans at numical dot com.

**Comment by numical** [comment]
@JustFly1984 - any files for me?
I suspect your issue is some template processing or other build after the plugin has done its work but I cannot be sure until I see your config and any template.  (I suspect *after* as your description suggests the first `<style>` element is the one added by the plugin - and this is added right at the end of `<head>`).

**Comment by numical** [comment]
No response so assume issue closed
